# Use an Ubuntu image or another suitable base image
# FROM ubuntu:20.04
FROM nvidia/cuda:12.6.3-devel-ubuntu20.04

# Set environment variables to avoid user interaction during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install required dependencies including CUDA toolkit
RUN apt update && apt install -y \
    build-essential \
    cmake \
    mesa-common-dev \
    git

# Copy dependency and build script into the container
COPY deploy_miner.sh .

# Make deploy script executable
RUN chmod +x deploy_miner.sh

# Run the script to build the binary
CMD ["./deploy_miner.sh"]
